- name: Update the machine
  ansible.builtin.apt:
    update_cache: yes   


- name: Install software-properties-common gnupg apt-transport-https ca-certificates
  package:
    name:
    - software-properties-common
    - gnupg
    - apt-transport-https
    - ca-certificates  
    - wget
    - curl
    - gnupg2
    - lsb-release
    state: present

- name: Import the public key used by the package management system
  shell: wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -

- name: Create a list file for MongoDB
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list

- name: IMport the libssl1.1
  shell: echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list


- name: Update the machine
  ansible.builtin.apt:
    update_cache: yes   

- name: Update the libssl1.1
  command: apt install libssl1.1

- name: Installation of mongodb-org
  package:
    name:  mongodb-org
    state: present
    update_cache: yes

- name: Start mongodb
  service:
    name: mongod
    state: started
    enabled: yes