- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Create default containers
  community.docker.docker_container:
    name: "{{ default_container_name }}"
    image: "{{ default_container_image }}"
    #volumes:
    #  - "/opt/mariadb/:/var/lib/mysql"
    ports:
      - "{{mysql_port}}:{{mysql_port}}"
    env:
      MYSQL_USER: "{{mysql_user}}"
      MYSQL_PASSWORD: "{{mysql_password}}"
      #PGDATA: "/var/lib/postgresql/data/pgdata"
      MYSQL_DATABASE: "{{mariadb_database}}"
