- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Create mariadb containers
  community.docker.docker_container:
    name: "{{ default_container_name }}"
    image: "{{ default_container_image }}"
    #volumes:
    #  - "/opt/mariadb/:/var/lib/mysql"
    ports:
      - "{{mariadb_port}}:{{mariadb_port}}"
    env:
      MYSQL_USER: "{{mariadb_user}}"
      MYSQL_PASSWORD: "{{mariadb_password}}"
      MARIADB_ROOT_PASSWORD: "{{mariadb_password}}"
      #PGDATA: "/var/lib/postgresql/data/pgdata"
      MYSQL_DATABASE: "{{mariadb_database}}"

