mariadb_user: user
mariadb_password: pass
mariadb_database: testdb
mariadb_version: present
install_docker: True
container_count: 1
default_container_name: mariadb
default_container_image: mariadb:{{mariadb_version}}
mariadb_port: 3306