- name: Update the machine
  ansible.builtin.apt:
    update_cache: yes     

- name: "Install packages"
  apt: "name={{ item }} state=present"
  with_items:
    - postgresql
    - postgresql-contrib
    - python3-psycopg2


- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data


- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql


- name: "Create app database"
  postgresql_db:
    state: present
    name: "{{ postgres_database }}"
  become: yes
  become_user: postgres

- name: "Create db user"
  postgresql_user:
    state: present
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
  become: yes
  become_user: postgres

- name: "Grant db user access to app db"
  postgresql_privs:
    type: database
    database: "{{ postgres_database }}"
    roles: "{{ postgres_user }}"
    grant_option: no
    privs: all
  become: yes
  become_user: postgres


- name: listenaddress to everyone
  shell: echo "listen_addresses = '*'" >> /etc/postgresql/14/main/postgresql.conf

- name: Add permissions pg_hba.conf
  shell: echo "host    all             all             0.0.0.0/0               scram-sha-256" >> /etc/postgresql/14/main/pg_hba.conf

- name: "Restart services"
  service: "name={{ item }} state=restarted enabled=yes"
  with_items:
    - postgresql